server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PATIENT
          uri: lb://PATIENT
          predicates:
            - Path=/patient/**
        - id: HOSPITAL
          uri: lb://HOSPITAL
          predicates:
            - Path=/hospital/**
       
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost