#server:
#  port: 8092
#spring:
# 
#  application:
#    name: HOSPITAL
#    
#  eureka:
#   client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#     defaultZone: http://localhost://8761/eureka
#   instance:
#     hostname: localhost
#     enableSelfPreservation: false
#      renewalPercentThreshold=0.33

server:
  port: 8071
spring:
  application:
    name: PARKING-SLOT

#
#  
#  instance:
#     hostname: localhost
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true
 